### PR TITLE
Create Best_time_to_buy_and_sell_stock.cpp

### PR DESCRIPTION
**Pull request by akshit397a**
**Best Time to Buy and Sell Stock using Greedy Approach => LeetCode Problem**

🟢 Objective :
Implement an efficient algorithm to maximize profit from buying and selling a stock on different days

🟢 Summary :
The naive solution with O(n²) time complexity results in Time Limit Exceeded (TLE) errors on larger datasets. The goal is to replace the nested loops with an O(n) greedy algorithm

Name: Akshit Agarwal(akshit397a)

### CODE REVIEW

**Comment by akshit397a** [comment]
Hey @Stormbreakerr20 , Kindly review this PR.

**Comment by Stormbreakerr20** [comment]
1. Mention your name and roll number in the PR description.
2. Please rename the file to leetcode_best_time_to_buy_and_sell_stock.cpp as mentioned in the [Contribution Guidelines].(https://github.com/KamandPrompt/HackQuest?tab=readme-ov-file#contribution-guidelines-)

**Comment by akshit397a** [comment]
> 1. Mention your name and roll number in the PR description.
> 2. Please rename the file to leetcode_best_time_to_buy_and_sell_stock.cpp as mentioned in the [Contribution Guidelines](https://github.com/KamandPrompt/HackQuest?tab=readme-ov-file#contribution-guidelines-)

may I know which roll number are you asking to mention??
@Stormbreakerr20

**Comment by akshit397a** [comment]
> 1. Mention your name and roll number in the PR description.
> 2. Please rename the file to leetcode_best_time_to_buy_and_sell_stock.cpp as mentioned in the [Contribution Guidelines](https://github.com/KamandPrompt/HackQuest?tab=readme-ov-file#contribution-guidelines-)

Rest all Changes done!
@Stormbreakerr20

**Pull request merged**
