### PR TITLE
BeginnerProblem1

### PR DESCRIPTION
**Pull request by r-vik**
- Added Beginner Problems Folder
- Added the first problem and solution within the folder

### CODE REVIEW

**Comment by r-vik** [comment]
PR by Aarvik Oberoi B23107

**Comment by Stormbreakerr20** [comment]
Please follow the file naming convention as mentioned in the [Contribution Guidelines](https://github.com/KamandPrompt/HackQuest?tab=readme-ov-file#contribution-guidelines-), your file name should be codeforces_2004A.cpp . Please be careful about upper/lower case in the file name.

**Comment by r-vik** [comment]
Done required changes

**Comment by r-vik** [comment]
Did the required changes.

**Comment by Stormbreakerr20** [comment]
> Did the required changes @Stormbreakerr20 .

Thanks for contributing.

**Pull request merged**
